[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[article]
  showWordCount = false
  showReadingTime = false
  showTableOfContents = true

[homepage]
  layout = "nomlab"
  showRecent = true