baseURL = 'https://nomlab.github.io/lab/nom'
locale = 'ja'
title = 'nomlab'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
  [markup.goldmark.parser.attribute]
    block = true

[[menu.main]]
name = "アクセス"
pageRef = "/access"
weight = 10

[[menu.main]]
name = "ノムニチ"
pageRef = "/articles"
weight = 20

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 30

[caches]
  [caches.images]
    dir = ':cacheDir/images'